//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcUMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyStudentPaymentSetup
    {
        public MonthlyStudentPaymentSetup()
        {
            this.StudentInvoiceLists = new HashSet<StudentInvoiceList>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SemesterId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> MonthId { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual ICollection<StudentInvoiceList> StudentInvoiceLists { get; set; }
    }
}
