//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcUMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyPaymentSetupDetail
    {
        public int Id { get; set; }
        public Nullable<int> PaymenSetupId { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<int> PayMonth { get; set; }
    
        public virtual StudentInvoiceList StudentInvoiceList { get; set; }
        public virtual StudentPaymentType StudentPaymentType { get; set; }
    }
}
