//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcUMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        public int Id { get; set; }
        public Nullable<int> PaymentTypeID { get; set; }
        public Nullable<decimal> Fees { get; set; }
        public Nullable<decimal> PayAmount { get; set; }
        public Nullable<System.Guid> PaymentsId { get; set; }
        public Nullable<int> PayMonth { get; set; }
    
        public virtual Payment Payment { get; set; }
        public virtual PaymentType PaymentType { get; set; }
    }
}
