//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcUMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public Payment()
        {
            this.PaymentDetails = new HashSet<PaymentDetail>();
        }
    
        public int AutoId { get; set; }
        public System.Guid Id { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.Guid> StudentId { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<decimal> Due { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
        public Nullable<int> BankId { get; set; }
        public string CheckNo { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
    
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
    }
}
