//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcUMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SchoolNewDBEntities : DbContext
    {
        public SchoolNewDBEntities()
            : base("name=SchoolNewDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Month> Months { get; set; }
        public DbSet<PaymentDetail> PaymentDetails { get; set; }
        public DbSet<PaymentMethod> PaymentMethods { get; set; }
        public DbSet<Payment> Payments { get; set; }
        public DbSet<PaymentType> PaymentTypes { get; set; }
        public DbSet<BankList> BankLists { get; set; }
        public DbSet<MonthlyStudentPaymentSetup> MonthlyStudentPaymentSetups { get; set; }
        public DbSet<StudentPaymentAmount> StudentPaymentAmounts { get; set; }
        public DbSet<StudentPaymentType> StudentPaymentTypes { get; set; }
        public DbSet<StudentInvoiceList> StudentInvoiceLists { get; set; }
        public DbSet<StudentPaymentCollection> StudentPaymentCollections { get; set; }
        public DbSet<MonthlyPaymentSetupDetail> MonthlyPaymentSetupDetails { get; set; }
    
        public virtual int GetPaymentDetails(string studentId)
        {
            var studentIdParameter = studentId != null ?
                new ObjectParameter("StudentId", studentId) :
                new ObjectParameter("StudentId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetPaymentDetails", studentIdParameter);
        }
    
        public virtual int GetStdPaymentDueList(string dept, string semesterId, string section)
        {
            var deptParameter = dept != null ?
                new ObjectParameter("dept", dept) :
                new ObjectParameter("dept", typeof(string));
    
            var semesterIdParameter = semesterId != null ?
                new ObjectParameter("semesterId", semesterId) :
                new ObjectParameter("semesterId", typeof(string));
    
            var sectionParameter = section != null ?
                new ObjectParameter("section", section) :
                new ObjectParameter("section", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetStdPaymentDueList", deptParameter, semesterIdParameter, sectionParameter);
        }
    
        public virtual int GetStudentPaymentList(Nullable<int> courseId, Nullable<int> semesterId)
        {
            var courseIdParameter = courseId.HasValue ?
                new ObjectParameter("courseId", courseId) :
                new ObjectParameter("courseId", typeof(int));
    
            var semesterIdParameter = semesterId.HasValue ?
                new ObjectParameter("semesterId", semesterId) :
                new ObjectParameter("semesterId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetStudentPaymentList", courseIdParameter, semesterIdParameter);
        }
    
        public virtual int StudentMarkInput(Nullable<int> courseId, string strSmt)
        {
            var courseIdParameter = courseId.HasValue ?
                new ObjectParameter("CourseId", courseId) :
                new ObjectParameter("CourseId", typeof(int));
    
            var strSmtParameter = strSmt != null ?
                new ObjectParameter("strSmt", strSmt) :
                new ObjectParameter("strSmt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StudentMarkInput", courseIdParameter, strSmtParameter);
        }
    }
}
