//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcUMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SchooldbEntities : DbContext
    {
        public SchooldbEntities()
            : base("name=SchooldbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public DbSet<Sp_StdAdvanceSearc_Result> sp_StdAdvanceSearcs { get; set; }

        public virtual ObjectResult<Sp_StdAdvanceSearc_Result> Sp_StdAdvanceSearc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_StdAdvanceSearc_Result>("Sp_StdAdvanceSearc");
        }

       
    }
}
