//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcUMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Student_info
    {
        public System.Guid Id { get; set; }
        public string Std_id { get; set; }
        public string Std_FName { get; set; }
        public string Std_MName { get; set; }
        public string Std_LName { get; set; }
        public string Father_Name { get; set; }
        public string Mother_Nmae { get; set; }
        public string Parmenent_address { get; set; }
        public string Present_address { get; set; }
        public string Picture { get; set; }
        public Nullable<System.DateTime> Birth_date { get; set; }
        public string Gender { get; set; }
        public string Contact_no { get; set; }
        public string Email_id { get; set; }
        public Nullable<System.DateTime> Admission_date { get; set; }
        public Nullable<System.DateTime> Entry_date { get; set; }
        public string status { get; set; }
        public string GardianName { get; set; }
        public string GardianMobile { get; set; }
        public string GardianOccupation { get; set; }
        public string GurdianRelation { get; set; }
        public string BeforeSchool { get; set; }
        public string BeforeClass { get; set; }
        public string BeforeGpa { get; set; }
        public Nullable<int> ProximateID { get; set; }
        public Nullable<int> SchoolId { get; set; }

        [NotMapped]
        public HttpPostedFileBase image { get; set; }
    }
}
