//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcUMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInvoiceList
    {
        public StudentInvoiceList()
        {
            this.StudentPaymentCollections = new HashSet<StudentPaymentCollection>();
            this.MonthlyPaymentSetupDetails = new HashSet<MonthlyPaymentSetupDetail>();
        }
    
        public int Id { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> DueAmount { get; set; }
        public Nullable<System.Guid> StudentId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> MonthlyPaymentSetupId { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> MonthId { get; set; }
        public Nullable<decimal> PreviousDue { get; set; }
    
        public virtual MonthlyStudentPaymentSetup MonthlyStudentPaymentSetup { get; set; }
        public virtual ICollection<StudentPaymentCollection> StudentPaymentCollections { get; set; }
        public virtual ICollection<MonthlyPaymentSetupDetail> MonthlyPaymentSetupDetails { get; set; }
    }
}
