//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcUMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPaymentType
    {
        public StudentPaymentType()
        {
            this.MonthlyPaymentSetupDetails = new HashSet<MonthlyPaymentSetupDetail>();
        }
    
        public int Id { get; set; }
        public string PaymentType { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual ICollection<MonthlyPaymentSetupDetail> MonthlyPaymentSetupDetails { get; set; }
    }
}
