//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcUMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class UMSEntities2 : DbContext
    {
        public UMSEntities2()
            : base("name=UMSEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Sp_studentAttendance_Result> Sp_studentAttendance()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_studentAttendance_Result>("Sp_studentAttendance");
        }
    }
}
