//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcUMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPaymentCollection
    {
        public int Id { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<int> StudentInvoiceId { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
        public Nullable<int> BankId { get; set; }
        public string CheckNo { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
    
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual StudentInvoiceList StudentInvoiceList { get; set; }
    }
}
